### ISSUE TITLE
插件无法正常加载

### ISSUE THREAD

**Issue by kazami-harutoki** [Colter23/bilibili-dynamic-mirai-plugin#10]
启动后直接报错，配置文件已按照说明填写，必填项齐全

![QQ截图20210421233402](https://user-images.githubusercontent.com/82960112/115581167-55351d00-a2fa-11eb-8e45-c49b0695b404.jpg)

**Comment by Colter23** [comment]
多试几次，这个是应该是插件运行时QQ还没登陆好，获取不到bot。可能是网络问题。

**Comment by kazami-harutoki** [comment]
> 多试几次，这个是应该是插件运行时QQ还没登陆好，获取不到bot。可能是网络问题。

已尝试多次，在MiraiCompose和Emg下均报错，挂不挂vpn，先登录账号和后登录账号都没有改变= =

**Comment by Colter23** [comment]
`Login successful` 是否在报错之后？

**Comment by kazami-harutoki** [comment]
> `Login successful` 是否在报错之后？

`E:\bot\emg>
@echo off
jre\bin\java -cp "./libs/*" net.mamoe.mirai.console.terminal.MiraiConsoleTerminalLoader 

[92m2021-04-22 12:41:07 I/main: Starting mirai-console...[0m[m
[92m2021-04-22 12:41:07 I/main: Backend: version 2.6.1, built on 2021-04-16 22:23:22.[0m[m
[92m2021-04-22 12:41:07 I/main: Frontend Terminal: version 2.6.1, provided by Mamoe Technologies[0m[m
[92m2021-04-22 12:41:07 I/main: Welcome to visit https://mirai.mamoe.net/[0m[m

[92m2021-04-22 12:41:07 I/plugin: Successfully loaded plugin BilibiliDynamic[0m[m
[92m2021-04-22 12:41:07 I/plugin: Successfully loaded plugin Chat Command[0m[m

[92m2021-04-22 12:41:07 I/main: Prepared built-in commands: autoLogin, help, login, permission, status, stop[0m[m
[92m2021-04-22 12:41:07 I/BilibiliDynamic: Plugin loaded[0m[m

[92m2021-04-22 12:41:07 I/BilibiliDynamic: forward......[0m[m
[92m2021-04-22 12:41:07 I/BilibiliDynamic: 初始化数据中...[0m[m
[92m2021-04-22 12:41:07 I/BilibiliDynamic: 初始化结束[0m[m

[92m2021-04-22 12:41:07 I/main: 2 plugin(s) enabled.[0m[m
[92m2021-04-22 12:41:07 I/main: mirai-console started successfully.[0m[m
> 

  
[31m2021-04-22 12:41:09 E/BilibiliDynamic: Exception in coroutine Plugin BilibiliDynamic of BilibiliDynamic
kotlin.UninitializedPropertyAccessException: lateinit property bot has not been initialized
	at top.colter.mirai.plugin.PluginMain.getBot(PluginMain.kt:38)
	at top.colter.mirai.plugin.PluginMain$onEnable$2.invokeSuspend(PluginMain.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[0m[m
`
检查了详细的日志，发现登录行为其实只是在图形界面上的，实际上报错以后就再也没有其他事件了。试着在MiraiCompose上运行，出现了同样的日志，然后再登录bot，出现
`Login successful`
之后尝试在指定的管理群（已授予过*.*权限）测试，chat command可以做出响应（我在群里打出/help命令），但在群里使用#开头的本插件命令均无任何反应。

**Comment by Colter23** [comment]
调整了下插件获取bot的逻辑 [releases](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/1.0.3) 里已更新   
可以再试试，请先登陆QQ，最好是自动登陆，插件一运行就会获取bot，之后会调整。

**Comment by kazami-harutoki** [comment]
> 调整了下插件获取bot的逻辑 [releases](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/1.0.3) 里已更新
> 可以再试试，请先登陆QQ，最好是自动登陆，插件一运行就会获取bot，之后会调整。

已可正常使用，辛苦了。
