### ISSUE TITLE
indeApi开启后频繁反馈错误

### ISSUE THREAD

**Issue by kissqianfu321** [Colter23/bilibili-dynamic-mirai-plugin#11]
错误提示 检测动态失败，2分钟后重试 null

config.yml:
admin: 809039746
exception: true
pushMode: 1
botState: true
basePath: '/DynamicPlugin'
font: 微软雅黑
friend: 
  enable: false
  agreeNewFriendRequest: true
  welcomeMessage: ( •̀ ω •́ )✧
group: 
  enable: true
  welcomeMemberJoin: true
  welcomeMessage: 欢迎
dynamic: 
  enable: true
  interval: 60
  lowSpeed: '200-800'
  videoMode: true
  saveDynamicImage: true
live: 
  enable: true
  indeApi: false
baiduTranslate: 
  enable: false
  APP_ID: ''
  SECURITY_KEY: ''
BPI: 
  dynamic: 'https://api.vc.bilibili.com/dynamic_svr/v1/dynamic_svr/space_history?visitor_uid=1111111111&offset_dynamic_id=0&need_top=0&host_uid='
  followNum: 'https://api.bilibili.com/x/relation/stat?vmid='
  liveStatus: 'https://api.live.bilibili.com/xlive/web-room/v1/index/getInfoByRoom?room_id='
  liveRoom: 'https://api.live.bilibili.com/room/v1/Room/getRoomInfoOld?mid='
  guard: 'https://api.live.bilibili.com/xlive/app-room/v2/guardTab/topList?page=1&page_size=1&'
  COOKIE: '_uuid=6FD7F0E5-9928-5753-FD4C-4917A05D8C0471851infoc'

pluginData.yml：
runPath: 'D:\Program Files (x86)\Mcl'
followList: 
  - 14897804
  - 2107634649
  - 519566923
  - 8199
  - 188662
  - 1818546038
  - 1436426333
  - 2113299278
groupList: {}

friendList: 
  809039746: 
    - 14897804@宴宁ccccc
    - 2107634649@费克の录屏组
    - 519566923@菜花花不是你的菜
    - 8199@紫苏九月
    - 188662@诺亚rococonorya
    - 1818546038@菜花花の录播组
    - 1436426333@诺亚の录屏组
    - 2113299278@小呜呜的小屋
followMemberGroup: 
  14897804: 
    - 809039746
  2107634649: 
    - 809039746
  519566923: 
    - 809039746
  8199: 
    - 809039746
  188662: 
    - 809039746
  1818546038: 
    - 809039746
  1436426333: 
    - 809039746
  2113299278: 
    - 809039746
userData: 
  - name: 宴宁ccccc
    uid: 14897804
    dynamicId: 520949541257695088
    liveRoom: 7953876
    liveStatus: 0
  - name: 费克の录屏组
    uid: 2107634649
    dynamicId: 521659735575725461
    liveRoom: 22880014
    liveStatus: 0
  - name: 菜花花不是你的菜
    uid: 519566923
    dynamicId: 521213329551726348
    liveRoom: 22211725
    liveStatus: 0
  - name: 紫苏九月
    uid: 8199
    dynamicId: 521187594109640070
    liveRoom: 598192
    liveStatus: 0
  - name: 诺亚rococonorya
    uid: 188662
    dynamicId: 519689402140040043
    liveRoom: 5211219
    liveStatus: 0
  - name: 菜花花の录播组
    uid: 1818546038
    dynamicId: 520640934973294503
    liveRoom: 0
    liveStatus: 0
  - name: 诺亚の录屏组
    uid: 1436426333
    dynamicId: 519430948196838383
    liveRoom: 0
    liveStatus: 0
  - name: 小呜呜的小屋
    uid: 2113299278
    dynamicId: 520262780278876625
    liveRoom: 0
    liveStatus: 0

**Comment by Colter23** [comment]
emmm具体原因还不知道，不过你的cookie最好用双引号括起来。  
[releases](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v1.0.4) 里更新了，修了一个小问题，不知道能不能解决你这个问题。先去试试吧
