### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by Hato626** [Colter23/bilibili-dynamic-mirai-plugin#15]
如题
![IMG_20210626_213850](https://user-images.githubusercontent.com/63497854/123514743-fbb8e800-d6c6-11eb-9c83-8a24c96a66d7.jpg)

**Comment by Colter23** [comment]
修了, 去 [releases](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v1.0.6) 里重新下载一遍吧
