### ISSUE TITLE
反馈“直播检测失败”

### ISSUE THREAD

**Issue by Echoosx** [Colter23/bilibili-dynamic-mirai-plugin#19]
v2.0.2版本，订阅B站账号后，有时会有如下报错
反馈信息：![image](https://user-images.githubusercontent.com/22994765/142918262-ba0efa13-b7d7-45a1-a898-2ff7b18be2f8.png)
控制台报错：![image](https://user-images.githubusercontent.com/22994765/142918029-75fc2588-e18a-4561-870a-883801170495.png)

**Comment by Colter23** [comment]
这就不是插件的问题了，应该是服务器的问题，内网网关出问题了。

**Comment by Echoosx** [comment]
使用v2.0.3版本后 不会再反馈这个错误了，辛苦
