### ISSUE TITLE
自动同意好友的欢迎语，配置无效

### ISSUE THREAD

**Issue by EdgeStar2020** [Colter23/bilibili-dynamic-mirai-plugin#2]
反馈一下，自动同意好友的功能没有问题，但是在同意好友之后自动发送的欢迎语内容变成了“true”，而在配置文件中的`welcomeMessage: "( •̀ ω •́ )✧"`项设置的内容没有得到应用。

**Comment by Colter23** [comment]
感谢反馈，已修复   ( •̀ ω •́ )✧
