### ISSUE TITLE
readme配置文件的信息和项目生成的不同。

### ISSUE THREAD

**Issue by FuYon** [Colter23/bilibili-dynamic-mirai-plugin#20]
这是配置文件里写的：
`cookie: ""`

这是生成的：
`cookie: ''`

**Comment by Colter23** [comment]
这不是我能掌控的，mirai应该还不能指定要生成的是双引号还是单引号    
其实要写成双引号的主要原因是因为b站的cookie中可能带有一个单引号（把那个引号删了也一样
