### ISSUE TITLE
问题反馈 动态过长导致图片推送失败

### ISSUE THREAD

**Issue by YehowahLiu** [Colter23/bilibili-dynamic-mirai-plugin#23]
对应动态链接
https://t.bilibili.com/606316848104740830

报错情况
![image](https://user-images.githubusercontent.com/52659312/146781466-d97a7b2c-aa71-408e-8b45-5958b0deacc6.png)
![image](https://user-images.githubusercontent.com/52659312/146781763-387040b1-221a-41d4-b916-384163c28889.png)

这个问题最麻烦的一点在于，如果有一条动态长度过长，bot可能会因此发出几十上百条重复报错消息

可能的解决办法：
- 捕获相关报错，下次检测到此动态时跳过不处理（下策）
- 对消息的长度和换行次数等进行判断，进行相应的简化后再生成图片推送（上策）

**Comment by Colter23** [comment]
已修复 [v2.0.6](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v2.0.6)
