### ISSUE TITLE
问题反馈 转发番剧的动态检测失败

### ISSUE THREAD

**Issue by YehowahLiu** [Colter23/bilibili-dynamic-mirai-plugin#24]
## 报错信息
![image](https://user-images.githubusercontent.com/52659312/147844772-1572cfea-4325-496f-a1c4-4b996f5a198a.png)
![image](https://user-images.githubusercontent.com/52659312/147844781-13869740-95c9-4e76-afba-05a59ffda8e4.png)

## 原动态地址：
https://t.bilibili.com/610617708089433128?tab=2

**Comment by Colter23** [comment]
emmm，我记得我修过这个问题来着。。可能修了但没完全修好。。之后再看看吧（

**Comment by YehowahLiu** [comment]
在 2.0.8 中已经修复
另外 在commit信息里加入 #24 可以自动关闭相应issue的（

**Comment by Colter23** [comment]
get
