### ISSUE TITLE
问题反馈 疑似emoji表情转发仍有问题

### ISSUE THREAD

**Issue by YehowahLiu** [Colter23/bilibili-dynamic-mirai-plugin#25]
我看最新的2.0.7说是可以正确处理emoji了，但是还是出了问题 ~~说不定我有bug体质~~

## 报错信息
![image](https://user-images.githubusercontent.com/52659312/147849345-70348d73-47de-4b66-a501-c60b804051b0.png)
## 动态链接：
https://t.bilibili.com/610729768086392619?tab=2

**Comment by YehowahLiu** [comment]
使用的是图片推送模式，插件版本2.0.7

**Comment by Colter23** [comment]
额，可能是emoji的问题，twitter的emoji可能没有这个emoji，或者是另外一个（我先把之前的2.0.8先撤了，再改一下

**Comment by YehowahLiu** [comment]
好的辛苦了

**Comment by Colter23** [comment]
临时解决了一下，如果没有这个emoji则仍会显示方块。目前这个好像也没有什么好的办法，不过大部分的emoji应该是有的（

**Comment by YehowahLiu** [comment]
光速解决，老大厉害！
