### ISSUE TITLE
添加代理选项

### ISSUE THREAD

**Issue by Initial-heart-1** [Colter23/bilibili-dynamic-mirai-plugin#28]
B 站 API 的访问间隔在 ＞10s 时是安全的，这是已经证明过的
那么，如果想达到更加低的延迟应该怎么办呢？
——没错，就是标题。
通过一个配置指定一个或多个代理服务器来实现更高频的访问
但是，又有人证明，高频访问 B 站 API 有几率被风控一段时间（无法访问）
所以可以考虑提供一些额外的配置项，比如：同时使用多少代理服务器、代理服务器在被风控后的休眠时间。
当无法正常访问时，则更换代理服务器，如果已经没有可以更换的代理服务器，则向管理员告警并暂停使用代理。
当然，这个 issue 并不是我的需求，对我来说多数情况下 10s 已经足够，只是有人实现过这样的功能所以提出 issue~~可以等 3.x 再说（~~
至于原仓库的位置，我怕有人说我引流，所以我不放了，Owner 想知道的话 B 站叫一下我

**Comment by Colter23** [comment]
之前有这个想法，不过太复杂就没实现
而且一般用户也不会去搞什么代理服务器
如果是从网络上自动爬那些免费的代理ip，自己用还行，但公开出来全都去用，估计也是不够的
那些免费的代理ip大概率也会被b站风控
（最近没大有时间写这个了，顶多修修bug，加点小功能

**Comment by Initial-heart-1** [comment]
> 之前有这个想法，不过太复杂就没实现 而且一般用户也不会去搞什么代理服务器 如果是从网络上自动爬那些免费的代理ip，自己用还行，但公开出来全都去用，估计也是不够的 那些免费的代理ip大概率也会被b站风控 （最近没大有时间写这个了，顶多修修bug，加点小功能

所以我说是 3.x，我也觉得这个麻烦
我也不知道为什么那人这么追求极限（汗）

**Comment by Colter23** [comment]
暂时不考虑代理了，之后如果需要我会 reopen
