### ISSUE TITLE
建议添加自动获取cookie

### ISSUE THREAD

**Issue by Initial-heart-1** [Colter23/bilibili-dynamic-mirai-plugin#34]
因为cookie是会失效的，而用户不一定总有时间去刷新cookie，这会导致出现一个很大的空窗期，这个期间服务是瘫痪的
但如果由插件自主检测状态并自动获取（刷新）就不会出现这样的问题了

**Comment by CauchyDOOM** [comment]
据我的日常使用b站的经验感觉b站cookies有效期是很久的，无论是二维码登录或是密码登录，长时间不敢说，1-2月内是不会变更的。(客服说只要不就进行敏感操作或者修改密码是不会失效的)

**Comment by Colter23** [comment]
差不多，我的小号cookie一直没换过（只要别退出登录啥的

**Comment by Initial-heart-1** [comment]
我也差不多，只是说有这个可能性，服务中断总是糟糕的，尽可能没有最好
