### ISSUE TITLE
建议优化图片模式绘图逻辑

### ISSUE THREAD

**Issue by Initial-heart-1** [Colter23/bilibili-dynamic-mirai-plugin#35]
众所周知，思源黑很全，但是并不好看
但是其他的字体部分极其特殊的符号（比如一些会在颜文字中用到的奇奇怪怪的语言的文字啥的）却没有，怎么解决呢？
当然是混合字体绘图！
给一个混合字体选项，要求需要配优先级且优先级不得相等
首先，在检测到字体有变动的时候对字体进行扫描，确定字体支持的字符
然后，在绘图时进行检测，从优先级最高的字体开始，遇到没有的字时检测下一级字体...以此类推，确定绘图顺序（此处如果出现字体全部使用也未能找到的情况，应抛出一个警告，但优先绘图并在图中加上“部分字符未能正常显示”或类似提示）
绘图时，将每个字体负责的部分同时开始渲染并等待全部渲染完成后将其合并（简单理解：类似于PS的图层）
这个很重要，务必**不要**在3.x实现，2.2可以（

**Comment by Initial-heart-1** [comment]
可能确实要费点脑子去搞~~，本来我是说交 pr，但是我 gradle 抽风了（~~

**Comment by Initial-heart-1** [comment]
未能完全实现，这关了，我不满意！（

**Comment by Colter23** [comment]
你想要啥效果。。。

**Comment by Initial-heart-1** [comment]
> 你想要啥效果。。。

oh，我说过罢
虽然目前方案能解决这个问题，但是用户感知是很明显的，你可以随便找不同字体的两张图对比看看，一眼不对劲
我是指，不支持的部分去找到优先级最高的能够支持这个字符的字体去显示
一会我画个图
