### ISSUE TITLE
无法订阅作为插件内账号的账号

### ISSUE THREAD

**Issue by Cicini** [Colter23/bilibili-dynamic-mirai-plugin#36]
当账号被作为插件内使用时，订阅该账号会提示关注失败

**Comment by Initial-heart-1** [comment]
@Colter23 这是一个逻辑 Bug
插件首先关注目标然后再去添加监测，来确保动态页面可以正确接受到目标的动态
但，这里有一个例外，就是这个账号本身
这个账号本身不可被自己关注，但其动态也会在动态页展示，确实应该考虑到这一点，尽管可能用得到的人不多
毕竟，你永远不知道用户会在酒吧点什么（
可以这样实现：要求用户填入该账号的 UID，在订阅时确定是否匹配，不匹配走现在的常规流程，匹配就跳过关注
另：@Cicini 在修复前你可以考虑直接写配置来实现你的需求，因为 #22 还未实装，理论可行，自行尝试
或者可以直接提交 Pull request
~~但 colter 一向很快的，你看到这条的时候说不定已经修了~~

**Comment by Initial-heart-1** [comment]
很遗憾，解决方案非常暴力（汗）

**Comment by Colter23** [comment]
这有啥暴力的，自动检测uid，总比让用户自己手填uid好吧。。

**Comment by Colter23** [comment]
还有，我在订阅数据里是预留了 跳过检测列表 `banList` ，不过这个是为了订阅账号全部关注使用的，用订阅全部账号可以从中踢出几个关注，不过这个功能现在被我禁用了。    
你在插件数据文件中就可以看到这些 `BiliSubscribeData.yml` 。第一项 name为 `ALL` 的就是订阅账号全部关注的数据。不过现在被我禁用了，就算你手动填了数据也没用。

**Comment by Colter23** [comment]
@Cicini 支持订阅账号本身了
