### ISSUE TITLE
建议增加一个筛选功能

### ISSUE THREAD

**Issue by MokouTyan** [Colter23/bilibili-dynamic-mirai-plugin#38]
插件真的很好看，朋友们都很喜欢~
但是经常会有下面这样情况出现，如果说能够根据规则转发动态就更好了
比如这种情况下，加入"-without 运营代转"这样的功能，就不转发带有“运营代转”内容的动态
![image](https://user-images.githubusercontent.com/40456395/151169015-8d3bff86-aaba-4572-824f-121e69d70c94.png)
<br>
或者说是下面这种情况，“-contain 数据结构”，只转发带“数据结构”题目的动态（考研的时候没看B站，插件当时帮了我很多忙，可以帮我看看王道的每日一题，但是它广告和直播还蛮多的，那些就很烦
![image](https://user-images.githubusercontent.com/40456395/151169589-b50e3e45-9b15-4702-91e5-7f20f75ac349.png)

**Comment by Initial-heart-1** [comment]
咋还整出带参来了？应该是写进配置吧
补充一下，建议提供一个“触发条件”设置，比如在动态开头检测到，结尾检测到，或者全文中一旦含有就触发，默认全文

**Comment by MokouTyan** [comment]
> 咋还整出带参来了？应该是写进配置吧 补充一下，建议提供一个“触发条件”设置，比如在动态开头检测到，结尾检测到，或者全文中一旦含有就触发，默认全文

嗯，除了包括内容条件以外，最好还要有内容排除条件，这样子就很完美啦~感谢开发，这个插件在我和朋友们考研的时候帮了大忙

**Comment by Colter23** [comment]
其实不大好搞，因为每个群或好友订阅每个人的需求不一样，所以就要对每群/好友的每个订阅进行单独的配置（通过指令进行配置。存储在数据文件中，而不是配置文件中）这样的话可能会更改存储的数据结构。

**Comment by Colter23** [comment]
@MokouTyan 大概实现了下，有很多问题，尤其是交互（先凑合着用吧  [v2.1.2](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v2.1.2)

**Comment by MokouTyan** [comment]
> @MokouTyan 大概实现了下，有很多问题，尤其是交互（先凑合着用吧 [v2.1.2](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v2.1.2)

辛苦了，我这段时间测试一下，如果有什么BUG的话会在这里留言，太感谢~

**Comment by Colter23** [comment]
哦，我才发现readme中指令列表中的尖括号参数有些消失了（离谱，已修复

**Comment by Colter23** [comment]
如有问题可新开issue
