### ISSUE TITLE
更换cookie后无法添加关注

### ISSUE THREAD

**Issue by CabbCat** [Colter23/bilibili-dynamic-mirai-plugin#40]
更换cookie后无法添加关注，提示关注失败。且删除插件和配置重新安装后仍有这个问题。

还有一个个人之前遇到的问题，插件在运行一段时间后会自动停止检测（通常是晚上测试还是好的，早上起来看控制台就已经停止检测了），mcl版本2.10.0-RC2,怀疑过是不是和另一个b站插件冲突但是删除另一个后还是有这个问题...

**Comment by Colter23** [comment]
首先查看控制台是否有错误信息（启动时与添加关注时）。没有报错的话就是cookie的问题，可以尝试退出后重新登录再次获取cookie，且获取后不要退出登录。    
关于插件停止检测还有待观察，之前我也遇到过几次，不过没抓到日志，而且最近我最近运行的也很稳定。（如果你能提供停止检测前的日志那就更好了（插件在会在debug级输出检测信息

**Comment by CabbCat** [comment]
cookie的问题我又试了一下，我小号0关注只有bot关注的几个人可以正常使用插件添加关注，大号1k2关注（没到上限，就会一直提示关注失败，且启动与添加关注时无error报错，能正常看到自己uid...

关于日志的问题，输出的检测信息是 D/BilibiliDynamic: LiveCheck  D/BilibiliDynamic: DynamicCheck这样的吗，还是有具体的信息呢（我不太清楚mcl要怎么改日志等级...mcl -c debug会报错，直接修改config/console/logger里的等级 控制台看着好像也没什么变化...)

**Comment by Colter23** [comment]
加我QQ吧，给你个测试版，再看看到底是啥错  3375582524

**Comment by Colter23** [comment]
使用新版添加用户如出现 `关注失败: 您的账号异常，请稍后再试` 则有可能b站账号被风控了

**Comment by qmzola** [comment]
@Colter23 我在Ubuntu新配置mirai的时候也遇到了本问题，不在cookie所属账号关注列表中的，会提示关注失败将log选择debug级别后内容为
/bili add 240374787                                                               2022-02-06 21:40:56 I/stdout: mid: 427563656                                            2022-02-06 21:40:56 I/stdout: uid: 240374787                                            2022-02-06 21:40:57 V/Bot.2707468673: Group(876530086) <- 关注失败

**Comment by qmzola** [comment]
> @Colter23 我在Ubuntu新配置mirai的时候也遇到了本问题，不在cookie所属账号关注列表中的，会提示关注失败将log选择debug级别后内容为 /bili add 240374787 2022-02-06 21:40:56 I/stdout: mid: 427563656 2022-02-06 21:40:56 I/stdout: uid: 240374787 2022-02-06 21:40:57 V/Bot.2707468673: Group(876530086) <- 关注失败

mirai版本为2.10.0-rc jdk版本不明(系统有11和17两个版本)Ubuntu版本为20.04 LTS

**Comment by qmzola** [comment]
> 

打错了，mirai版本是2.10.0，无rc

**Comment by Colter23** [comment]
@qmzola 请使用新版再次尝试，新版增加了关注失败的原因

**Comment by Initial-heart-1** [comment]
> > @Colter23 我在Ubuntu新配置mirai的时候也遇到了本问题，不在cookie所属账号关注列表中的，会提示关注失败将log选择debug级别后内容为 /bili add 240374787 2022-02-06 21:40:56 I/stdout: mid: 427563656 2022-02-06 21:40:56 I/stdout: uid: 240374787 2022-02-06 21:40:57 V/Bot.2707468673: Group(876530086) <- 关注失败
> 
> mirai版本为2.10.0-rc jdk版本不明(系统有11和17两个版本)Ubuntu版本为20.04 LTS

Debug 等级为什么混进来一个 Verbose？（这不是重点）
先更新到插件最新版本，问题依旧的话重新传一下日志

**Comment by qmzola** [comment]
> 

提示账号异常(哭)

**Comment by Initial-heart-1** [comment]
> > 
> 
> 提示账号异常(哭)

更换账号试试，风控

**Comment by qmzola** [comment]
> > > @Colter23 我在Ubuntu新配置mirai的时候也遇到了本问题，不在cookie所属账号关注列表中的，会提示关注失败将log选择debug级别后内容为 /bili add 240374787 2022-02-06 21:40:56 I/stdout: mid: 427563656 2022-02-06 21:40:56 I/stdout: uid: 240374787 2022-02-06 21:40:57 V/Bot.2707468673: Group(876530086) <- 关注失败
> > 
> > 
> > mirai版本为2.10.0-rc jdk版本不明(系统有11和17两个版本)Ubuntu版本为20.04 LTS
> 
> Debug 等级为什么混进来一个 Verbose？（这不是重点） 先更新到插件最新版本，问题依旧的话重新传一下日志

log为

2022-02-07 21:57:38 D/BilibiliDynamic: DynamicCheck
2022-02-07 21:57:46 V/Bot.2707468673: [1⃣️烻佬の动态壁纸交流1群(876530086)] 洛基(2557354501) -> /bili add 240374787
2022-02-07 21:57:47 V/Bot.2707468673: Group(876530086) <- 关注失败: 您的账号异常，请稍后再试                                                                                    2022-02-07 21:57:51 D/BilibiliDynamic: DynamicCheck

**Comment by Initial-heart-1** [comment]
> > > > @Colter23 我在Ubuntu新配置mirai的时候也遇到了本问题，不在cookie所属账号关注列表中的，会提示关注失败将log选择debug级别后内容为 /bili add 240374787 2022-02-06 21:40:56 I/stdout: mid: 427563656 2022-02-06 21:40:56 I/stdout: uid: 240374787 2022-02-06 21:40:57 V/Bot.2707468673: Group(876530086) <- 关注失败
> > > 
> > > 
> > > mirai版本为2.10.0-rc jdk版本不明(系统有11和17两个版本)Ubuntu版本为20.04 LTS
> > 
> > 
> > Debug 等级为什么混进来一个 Verbose？（这不是重点） 先更新到插件最新版本，问题依旧的话重新传一下日志
> 
> log为
> 
> 2022-02-07 21:57:38 D/BilibiliDynamic: DynamicCheck 2022-02-07 21:57:46 V/Bot.2707468673: [1⃣️烻佬の动态壁纸交流1群(876530086)] 洛基(2557354501) -> /bili add 240374787 2022-02-07 21:57:47 V/Bot.2707468673: Group(876530086) <- 关注失败: 您的账号异常，请稍后再试 2022-02-07 21:57:51 D/BilibiliDynamic: DynamicCheck

网络环境能说一下吗，ISP和带宽，云服务器的话说一下服务商、带宽和位置

**Comment by qmzola** [comment]
> > > > > @Colter23 我在Ubuntu新配置mirai的时候也遇到了本问题，不在cookie所属账号关注列表中的，会提示关注失败将log选择debug级别后内容为 /bili add 240374787 2022-02-06 21:40:56 I/stdout: mid: 427563656 2022-02-06 21:40:56 I/stdout: uid: 240374787 2022-02-06 21:40:57 V/Bot.2707468673: Group(876530086) <- 关注失败
> > > > 
> > > > 
> > > > mirai版本为2.10.0-rc jdk版本不明(系统有11和17两个版本)Ubuntu版本为20.04 LTS
> > > 
> > > 
> > > Debug 等级为什么混进来一个 Verbose？（这不是重点） 先更新到插件最新版本，问题依旧的话重新传一下日志
> > 
> > 
> > log为
> > 2022-02-07 21:57:38 D/BilibiliDynamic: DynamicCheck 2022-02-07 21:57:46 V/Bot.2707468673: [1⃣️烻佬の动态壁纸交流1群(876530086)] 洛基(2557354501) -> /bili add 240374787 2022-02-07 21:57:47 V/Bot.2707468673: Group(876530086) <- 关注失败: 您的账号异常，请稍后再试 2022-02-07 21:57:51 D/BilibiliDynamic: DynamicCheck
> 
> 网络环境能说一下吗，ISP和带宽，云服务器的话说一下服务商、带宽和位置

上海阿里云，1mbps

**Comment by qmzola** [comment]
> 

没有换Linux之前一切正常

**Comment by Initial-heart-1** [comment]
> > > > > > @Colter23 我在Ubuntu新配置mirai的时候也遇到了本问题，不在cookie所属账号关注列表中的，会提示关注失败将log选择debug级别后内容为 /bili add 240374787 2022-02-06 21:40:56 I/stdout: mid: 427563656 2022-02-06 21:40:56 I/stdout: uid: 240374787 2022-02-06 21:40:57 V/Bot.2707468673: Group(876530086) <- 关注失败
> > > > > 
> > > > > 
> > > > > mirai版本为2.10.0-rc jdk版本不明(系统有11和17两个版本)Ubuntu版本为20.04 LTS
> > > > 
> > > > 
> > > > Debug 等级为什么混进来一个 Verbose？（这不是重点） 先更新到插件最新版本，问题依旧的话重新传一下日志
> > > 
> > > 
> > > log为
> > > 2022-02-07 21:57:38 D/BilibiliDynamic: DynamicCheck 2022-02-07 21:57:46 V/Bot.2707468673: [1⃣️烻佬の动态壁纸交流1群(876530086)] 洛基(2557354501) -> /bili add 240374787 2022-02-07 21:57:47 V/Bot.2707468673: Group(876530086) <- 关注失败: 您的账号异常，请稍后再试 2022-02-07 21:57:51 D/BilibiliDynamic: DynamicCheck
> > 
> > 
> > 网络环境能说一下吗，ISP和带宽，云服务器的话说一下服务商、带宽和位置
> 
> 上海阿里云，1mbps

cookie 是你本地获取然后写进配置的是吗

**Comment by Initial-heart-1** [comment]
> > > > > > > > @Colter23 我在Ubuntu新配置mirai的时候也遇到了本问题，不在cookie所属账号关注列表中的，会提示关注失败将log选择debug级别后内容为 /bili add 240374787 2022-02-06 21:40:56 I/stdout: mid: 427563656 2022-02-06 21:40:56 I/stdout: uid: 240374787 2022-02-06 21:40:57 V/Bot.2707468673: Group(876530086) <- 关注失败
> > > > > > > 
> > > > > > > 
> > > > > > > mirai版本为2.10.0-rc jdk版本不明(系统有11和17两个版本)Ubuntu版本为20.04 LTS
> > > > > > 
> > > > > > 
> > > > > > Debug 等级为什么混进来一个 Verbose？（这不是重点） 先更新到插件最新版本，问题依旧的话重新传一下日志
> > > > > 
> > > > > 
> > > > > log为
> > > > > 2022-02-07 21:57:38 D/BilibiliDynamic: DynamicCheck 2022-02-07 21:57:46 V/Bot.2707468673: [1⃣️烻佬の动态壁纸交流1群(876530086)] 洛基(2557354501) -> /bili add 240374787 2022-02-07 21:57:47 V/Bot.2707468673: Group(876530086) <- 关注失败: 您的账号异常，请稍后再试 2022-02-07 21:57:51 D/BilibiliDynamic: DynamicCheck
> > > > 
> > > > 
> > > > 网络环境能说一下吗，ISP和带宽，云服务器的话说一下服务商、带宽和位置
> > > 
> > > 
> > > 上海阿里云，1mbps
> > 
> > 
> > cookie 是你本地获取然后写进配置的是吗
> 
> 是他人帮忙获取，但人不在上海

可能是异地的问题，你可以试试用服务器直接获取 cookie 现取现用

**Comment by qmzola** [comment]
> > > > > > > > > @Colter23 我在Ubuntu新配置mirai的时候也遇到了本问题，不在cookie所属账号关注列表中的，会提示关注失败将log选择debug级别后内容为 /bili add 240374787 2022-02-06 21:40:56 I/stdout: mid: 427563656 2022-02-06 21:40:56 I/stdout: uid: 240374787 2022-02-06 21:40:57 V/Bot.2707468673: Group(876530086) <- 关注失败
> > > > > > > > 
> > > > > > > > 
> > > > > > > > mirai版本为2.10.0-rc jdk版本不明(系统有11和17两个版本)Ubuntu版本为20.04 LTS
> > > > > > > 
> > > > > > > 
> > > > > > > Debug 等级为什么混进来一个 Verbose？（这不是重点） 先更新到插件最新版本，问题依旧的话重新传一下日志
> > > > > > 
> > > > > > 
> > > > > > log为
> > > > > > 2022-02-07 21:57:38 D/BilibiliDynamic: DynamicCheck 2022-02-07 21:57:46 V/Bot.2707468673: [1⃣️烻佬の动态壁纸交流1群(876530086)] 洛基(2557354501) -> /bili add 240374787 2022-02-07 21:57:47 V/Bot.2707468673: Group(876530086) <- 关注失败: 您的账号异常，请稍后再试 2022-02-07 21:57:51 D/BilibiliDynamic: DynamicCheck
> > > > > 
> > > > > 
> > > > > 网络环境能说一下吗，ISP和带宽，云服务器的话说一下服务商、带宽和位置
> > > > 
> > > > 
> > > > 上海阿里云，1mbps
> > > 
> > > 
> > > cookie 是你本地获取然后写进配置的是吗
> > 
> > 
> > 是他人帮忙获取，但人不在上海
> 
> 可能是异地的问题，你可以试试用服务器直接获取 cookie 现取现用

所以说Linux怎么获取cookie()

**Comment by Initial-heart-1** [comment]
> > > > > > > > > > @Colter23 我在Ubuntu新配置mirai的时候也遇到了本问题，不在cookie所属账号关注列表中的，会提示关注失败将log选择debug级别后内容为 /bili add 240374787 2022-02-06 21:40:56 I/stdout: mid: 427563656 2022-02-06 21:40:56 I/stdout: uid: 240374787 2022-02-06 21:40:57 V/Bot.2707468673: Group(876530086) <- 关注失败
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > mirai版本为2.10.0-rc jdk版本不明(系统有11和17两个版本)Ubuntu版本为20.04 LTS
> > > > > > > > 
> > > > > > > > 
> > > > > > > > Debug 等级为什么混进来一个 Verbose？（这不是重点） 先更新到插件最新版本，问题依旧的话重新传一下日志
> > > > > > > 
> > > > > > > 
> > > > > > > log为
> > > > > > > 2022-02-07 21:57:38 D/BilibiliDynamic: DynamicCheck 2022-02-07 21:57:46 V/Bot.2707468673: [1⃣️烻佬の动态壁纸交流1群(876530086)] 洛基(2557354501) -> /bili add 240374787 2022-02-07 21:57:47 V/Bot.2707468673: Group(876530086) <- 关注失败: 您的账号异常，请稍后再试 2022-02-07 21:57:51 D/BilibiliDynamic: DynamicCheck
> > > > > > 
> > > > > > 
> > > > > > 网络环境能说一下吗，ISP和带宽，云服务器的话说一下服务商、带宽和位置
> > > > > 
> > > > > 
> > > > > 上海阿里云，1mbps
> > > > 
> > > > 
> > > > cookie 是你本地获取然后写进配置的是吗
> > > 
> > > 
> > > 是他人帮忙获取，但人不在上海
> > 
> > 
> > 可能是异地的问题，你可以试试用服务器直接获取 cookie 现取现用
> 
> 所以说Linux怎么获取cookie()

装个 GUI，然后远程用 Firefox 访问 B 站并登录，然后看 F12
当然 CLI 应该也行，不过你都这么问了肯定不会用，老实用 GUI 吧

**Comment by Colter23** [comment]
不至于。。。

**Comment by Initial-heart-1** [comment]
> 不至于。。。

就试试，万一成了呢（）

**Comment by qmzola** [comment]
> > 不至于。。。
> 
> 就试试，万一成了呢（）

我还是换回Windows sever吧

**Comment by Colter23** [comment]
还不够折腾的。。不如新注册个账号

**Comment by Initial-heart-1** [comment]
总不能，B 站因为 IP 是阿里云的直接风控吧（）

**Comment by qmzola** [comment]
> 总不能，B 站因为 IP 是阿里云的直接风控吧（）

主要是我之前用Windows sever的时候可以(没备份cookie的屑)

**Comment by Initial-heart-1** [comment]
> 还不够折腾的。。不如新注册个账号

所以快去做自动获取 cookie，需求来了！
（这不还在验证吗）

**Comment by qmzola** [comment]
> > 总不能，B 站因为 IP 是阿里云的直接风控吧（）
> 
> 主要是我之前用Windows sever的时候可以(没备份cookie的屑)

最近换Ubuntu才有这个问题

**Comment by Initial-heart-1** [comment]
> > 总不能，B 站因为 IP 是阿里云的直接风控吧（）
> 
> 主要是我之前用Windows sever的时候可以(没备份cookie的屑)

用 winserver 的时候 cookie 怎么获取的呢

**Comment by qmzola** [comment]
> > > 总不能，B 站因为 IP 是阿里云的直接风控吧（）
> > 
> > 
> > 主要是我之前用Windows sever的时候可以(没备份cookie的屑)
> 
> 用 winserver 的时候 cookie 怎么获取的呢

edge f12

**Comment by qmzola** [comment]
> > > > > 总不能，B 站因为 IP 是阿里云的直接风控吧（）
> > > > 
> > > > 
> > > > 主要是我之前用Windows sever的时候可以(没备份cookie的屑)
> > > 
> > > 
> > > 用 winserver 的时候 cookie 怎么获取的呢
> > 
> > 
> > edge f12
> 
> 在服务器上获取的是吗

是的

**Comment by Initial-heart-1** [comment]
> > > > > > 总不能，B 站因为 IP 是阿里云的直接风控吧（）
> > > > > 
> > > > > 
> > > > > 主要是我之前用Windows sever的时候可以(没备份cookie的屑)
> > > > 
> > > > 
> > > > 用 winserver 的时候 cookie 怎么获取的呢
> > > 
> > > 
> > > edge f12
> > 
> > 
> > 在服务器上获取的是吗
> 
> 是的

那可能破案了，不用换，别急

**Comment by Colter23** [comment]
你bot用的号跟你平时用的号是同一个吗
你先停一下 @Initial-heart-1

**Comment by Initial-heart-1** [comment]
> 你bot用的号跟你平时用的号是同一个吗 你先停一下 @Initial-heart-1

当然不是，之前是，但是因为动态太多了换了个新号，都没有出现问题
服务器跟我是在同一个城市的

**Comment by Initial-heart-1** [comment]
wait，真就把 GitHub 当 IM 用了啊

**Comment by Colter23** [comment]
不是问你，但是让你停一下，先我让问 @Initial-heart-1

**Comment by Initial-heart-1** [comment]
> 不是问你，但是让你停一下，先我让问 @Initial-heart-1

OK

**Comment by qmzola** [comment]
> 你bot用的号跟你平时用的号是同一个吗 你先停一下 @Initial-heart-1

是的()

**Comment by Initial-heart-1** [comment]
噔噔咚

**Comment by Initial-heart-1** [comment]
我理解为什么风控了，而且可能很难解决

**Comment by qmzola** [comment]
> 换个新号吧

好的谢谢

**Comment by Colter23** [comment]
长期多次异地登录，会被b站怀疑的，建议再开个小号，不用答题，手机号注册即可

**Comment by Colter23** [comment]
> 

不要发些没用的评论，说话一下子说完。这不是聊天的地方

**Comment by Initial-heart-1** [comment]
> > 
> 
> 不要发些没用的评论，说话一下子说完。这不是聊天的地方

但是叠回车很怪（）

**Comment by Initial-heart-1** [comment]
> 上面没用的评论我等会会删掉，方便后面的人查看

不用你，我来（汗）

**Comment by Initial-heart-1** [comment]
> 哦干，怎么这么多叉号。。。

你才知道会有提示的吗，所以我才说我自己删啊

**Comment by qmzola** [comment]
> 长期多次异地登录，会被b站怀疑的，建议再开个小号，不用答题，手机号注册即可

当我今天开了小号之后，居然还是"关注失败: 您的账号异常，请稍后再试"
