### ISSUE TITLE
行数过少且不带图片，自适应宽度的建议

### ISSUE THREAD

**Issue by MokouTyan** [Colter23/bilibili-dynamic-mirai-plugin#45]
![Screenshot_20220302-145820~2](https://user-images.githubusercontent.com/40456395/156311682-3551043e-519c-4787-94c7-070dcca8dc6c.png)
动态里如果行数过低，类似于晚晚和贝拉这样的动态，自适应宽度的话可以不用点开图来看
感谢开发~

**Comment by MokouTyan** [comment]
图上有其他两种不同情况
星瞳的每行虽然少，但是行数比较多
文静虽然只有一行，但是带图片
就不会发生这样的情况

**Comment by Colter23** [comment]
高度问题，可以试试新版，加了个页脚，能高一点（

**Comment by Colter23** [comment]
暂时不准备解决了，等之后可能会重构绘图代码时再说
