### ISSUE TITLE
图片未加载完成显示空白

### ISSUE THREAD

**Issue by hhhfsj** [Colter23/bilibili-dynamic-mirai-plugin#48]
可以让图片加载完整之后再合成嘛
![QQ截图20220324201553](https://user-images.githubusercontent.com/47785500/159914272-4a48584c-3103-4da4-a884-9577566c012a.png)

**Comment by Colter23** [comment]
是gif，有时候加载不出来，之后我再看看

**Comment by Colter23** [comment]
@hhhfsj 试试新版 (v2.2.1-RC1)[https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v2.2.1-RC1]

**Comment by Colter23** [comment]
[v2.2.1](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v2.2.1)
