### ISSUE TITLE
功能建议 自定义图片分辨率

### ISSUE THREAD

**Issue by haha114514** [Colter23/bilibili-dynamic-mirai-plugin#49]

**Comment by haha114514** [comment]
类似于系统显示中的高DPI缩放（HiDPI）。可以自行提升渲染精度来提升渲染出图片的画质（分辨率）或者在低配设备上降低渲染精度来降低负载。

**Comment by haha114514** [comment]
在config里面添加一个设置，1.0的时候就是保持现在默认的参数，2.0就是按照之前的2倍分辨率渲染。

**Comment by Colter23** [comment]
嫌分辨率太低吗。我觉得这个分辨率正好（宽度800px），一般图片大小不会太大（几百kb）。如果再大的话一张图片就要按mb计了，这样的大小在qq上显示如果网络不是太好可能要加载一会。

不过既然你有这个需求，之后可以考虑自定义分辨率，现在默认的是宽度固定800px。

**Comment by haha114514** [comment]
是有点强迫症了，日常看惯了手机和4k屏幕，再去看这个觉得字体渲染有点虚（分辨率太低），有能自己调整的是最好的。

**Comment by Colter23** [comment]
这个有点麻烦，有些元素位置跟大小是写死的，改起来有点麻烦（有点想重构，暂时搁置一下吧

**Comment by haha114514** [comment]
好的

**Comment by Colter23** [comment]
@haha114514 你预期的分辨率是多少（我电脑才1080p的分辨率，没用过那么高的分辨率，所以问一下
这分辨率也不能太高，太高的话如果动态中有图可能就要强行放大，可能会糊

**Comment by haha114514** [comment]
宽度1200px左右？

**Comment by Colter23** [comment]
更新了测试版 [v3.0.0-M1](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.0.0-M1)
