### ISSUE TITLE
二维码的建议

### ISSUE THREAD

**Issue by MokouTyan** [Colter23/bilibili-dynamic-mirai-plugin#51]
图片不带文字，在群聊里面比较整洁美观（图片+链接的模式，在PC端看上去还好，在手机端看上去非常臃肿
![}@TX~WE5R$I{HVU4$U)3RY1](https://user-images.githubusercontent.com/40456395/161310478-13d867ac-1ac2-4aad-b493-4633212aabcf.png)
但是纯图片模式也有缺点，如果想看视频/动态的评论的话，就得手动打开B站搜索（会稍微麻烦些
所以建议在config里面选择是否开启二维码，这样子可以直接在QQ里面识别二维码，直接打开B站看评论，方便很多
（昨天塔菲在B站炒作，Bot发群里了，但是我没关注她，我就得特意开B站去搜索，有一点麻烦
![(KXK5GUP1E HZTQL09K5J17](https://user-images.githubusercontent.com/40456395/161312259-c8de3c45-b369-4d67-b474-4d9f133a66c2.png)
二维码最好是可以和选择的主题色相同（或者介于外框主题色和内容的背景色之间，我这里简单做了张图
![2](https://user-images.githubusercontent.com/40456395/161311657-0385f32a-ea7b-4bc8-bf58-aa972a6f9ca9.png)
感谢开发~

**Comment by MokouTyan** [comment]
直播间也一样，可以直接识别二维码打开，
![3](https://user-images.githubusercontent.com/40456395/161314554-3d415d75-9650-4829-81f8-91ef54ee8ced.png)
原本是这样的
![(0L_U2Z7 _(DZWF)V31Y7_U](https://user-images.githubusercontent.com/40456395/161314638-f6c57fa3-8afc-4efb-95f3-2a6f257ea859.png)

**Comment by MokouTyan** [comment]
直播间也是一样的，可以直接识别二维码打开B站
原本是这样的
![(0L_U2Z7 _(DZWF)V31Y7_U](https://user-images.githubusercontent.com/40456395/161315096-7812b8c3-ccc1-42d5-be99-5b1c0768ebc6.png)
修改成这样子
![3](https://user-images.githubusercontent.com/40456395/161315231-605765dd-56bd-4175-af11-d68680edc796.png)

**Comment by MokouTyan** [comment]
这个是B站官方生成的海报
![97A11912B354E9C454D6E42CBD2FD964](https://user-images.githubusercontent.com/40456395/161315744-46b1192e-7d7c-4023-ba35-0b3e46a0ef74.jpg)

**Comment by MokouTyan** [comment]
![6](https://user-images.githubusercontent.com/40456395/161319437-07965268-e2b5-4d0e-af07-cb92809666e7.png)
我自己也蛮修改了一下，估计是深浅介于两者颜色之间，观感效果最好，同时机器还能识别出二维码
我试了比内容的背景色还浅的背景色，机器无法识别到二维码存在了

**Comment by Colter23** [comment]
感觉你的背景颜色都太深了（

**Comment by MokouTyan** [comment]
> 感觉你的背景颜色都太深了（

雪莲大佐的主题色是白色捏~

**Comment by MokouTyan** [comment]
![-5fe22e726aeb46a7](https://user-images.githubusercontent.com/40456395/161365036-2e31762c-d4b0-4ae8-873d-031573e8da2a.jpg)

**Comment by MokouTyan** [comment]
> 感觉你的背景颜色都太深了（

二维码有个容错机制，容错越高二维码图像越复杂，所以二维码功能加入后，可以选择不容错，看上去会简约些，也能使二维码更好被识别（因为是机器内对图像扫码，而不是实际用相机扫码，可以不用考虑容错）
以下是7%和30%，图像的复杂度
![image](https://user-images.githubusercontent.com/40456395/161368570-089b1b3a-953a-47f2-8afe-8620054be66d.png)
![image](https://user-images.githubusercontent.com/40456395/161368590-60d2aaf5-9690-4eb5-82c2-f262461a2d69.png)
还有个码点和码眼圆角生成的问题，圆角是很好看，比较契合图像，但是可能开发会难很多
![image](https://user-images.githubusercontent.com/40456395/161368671-4263b81a-36df-478a-860b-761c877109ae.png)
最后感谢开发ww

**Comment by Colter23** [comment]
容错我知道。但二维码美化我用的那个框架并不支持（ZXing）

**Comment by MokouTyan** [comment]
> 容错我知道。但二维码美化我用的那个框架并不支持（ZXing）

主要难点还是怎么把二维码内容转成主题色，还有把白底抠掉，加油捏~
![GKXOP$IBOMA }{K9T0Y)% L](https://user-images.githubusercontent.com/40456395/161375665-d78f1cdb-869f-42a2-8c3a-778ed04846d6.jpg)

**Comment by Colter23** [comment]
[v2.2.1](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v2.2.1)
