### ISSUE TITLE
无法转发直播的动态

### ISSUE THREAD

**Issue by MEYUYU** [Colter23/bilibili-dynamic-mirai-plugin#53]
无法转发直播的动态,出现如下报错
![2d2be938921bc88024f99bb3d442d35](https://user-images.githubusercontent.com/3656262/162098099-a97b7eb0-907d-4f4f-a9a7-ba843b8dee30.jpg)
![9ef97f5e1a14dbcbb28538d8c16ffe3](https://user-images.githubusercontent.com/3656262/162098107-0531284c-f58a-48c2-bc68-9319de2a4375.png)

**Comment by Colter23** [comment]
用的文字模式吗（

**Comment by MEYUYU** [comment]
是文字模式

**Comment by Colter23** [comment]
[v2.2.2-M1](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v2.2.2-M1)

**Comment by MEYUYU** [comment]
文字模式转发直播动态变成这样了
![image](https://user-images.githubusercontent.com/3656262/162341781-5d61dff7-5114-4928-a342-5d6f2d71ce06.png)
请留意一下这里
![image](https://user-images.githubusercontent.com/3656262/162341829-069e7d15-d0dc-4228-9e4d-4b6e7d2f0dbe.png)

**Comment by Colter23** [comment]
少了个大括号（绷不住了    
更新了文件，去重新下一遍吧 -> [v2.2.2-M1](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v2.2.2-M1)
