### ISSUE TITLE
筛选模式下，在控制台重复检测新动态

### ISSUE THREAD

**Issue by MokouTyan** [Colter23/bilibili-dynamic-mirai-plugin#54]
只是测试
![image](https://user-images.githubusercontent.com/40456395/162738853-5a260780-db75-446a-b5db-e0c692ae3e11.png)
![QJ6ONX@33V%1$P W7WB}L6P](https://user-images.githubusercontent.com/40456395/162739008-01f4ff61-c27f-434d-8aa0-9e575057a64a.png)

**Comment by Colter23** [comment]
这个我知道，影响不大

**Comment by MokouTyan** [comment]
![image](https://user-images.githubusercontent.com/40456395/164188805-aec4a874-64f5-4096-b5e3-8354f33429b5.png)
日志消息太多了，因为我把运营两个字屏蔽了hhh

**Comment by Colter23** [comment]
https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v2.2.2
