### ISSUE TITLE
设置默认颜色，以及订阅名字的建议

### ISSUE THREAD

**Issue by MokouTyan** [Colter23/bilibili-dynamic-mirai-plugin#55]
建议在config里面增加默认颜色选项

从用户角度考虑，群友们觉得去B站订阅uid挺麻烦的，希望可以直接
/bili add 名字
然后后台转为uid

**Comment by Colter23** [comment]
主要是名字如果输入不全的话可能不唯一（一般都输不全），再次进行选择的话还有可能选错（总之是挺麻烦的。    
等下一次重构吧，再搞通过名字订阅

**Comment by MokouTyan** [comment]
名字的话一般是完全匹配的吧，不会在聊天界面搜索，
/bili del 用户名
应该也可以，这样就可以不先用/bili list查看了
