### ISSUE TITLE
单图自适应建议

### ISSUE THREAD

**Issue by MokouTyan** [Colter23/bilibili-dynamic-mirai-plugin#57]
![image](https://user-images.githubusercontent.com/40456395/163659011-287af245-7325-440c-bdc0-00b33c5665a5.png)
单图希望可以显示完整图片（根据图片的宽度自适应，再判断图片高度，现在横长条照片没怎么见过

**Comment by Colter23** [comment]
@MokouTyan V3样式怎样（ https://github.com/Colter23/bilibili-dynamic-mirai-plugin/tree/v3#v3%E7%89%88%E6%9C%AC%E9%87%8D%E6%9E%84%E4%B8%AD

**Comment by MokouTyan** [comment]
V3整体框架挺好看的，实际放在手机QQ上，有一种卡片浮动在聊天窗口上的感觉
我发在群里，也和朋友讨论了一下，整理出以下建议
》无论是动态id还是av号都有些太靓眼的感觉了（因为平时大家只关注内容，像是这些后台id实际上大家并不关心，可以选择是否开启吧）
》投稿视频的播放数和弹幕数可以不用显示，因为如果不是转发的话，观看数和弹幕数都很低
》右上角那个数字牌子感觉上是可以不用显示的（我觉得数字牌子就是b站的败笔，vup的话一般是000001号，也是会有些影响观看内容的感觉吧）以前那个二维码就挺好的，非常实用，所以建议右上角修改为三选一（牌子、二维码、空）
》背景好像是改成渐变色的，感觉设置颜色的渐变，需要你找一个好看的算法~因为普通用户估计设置颜色的话只会设置单色（右上到左下的对角线主轴为用户设置颜色，然后主轴往外颜色渐变浅色会不会好一些？
》字体为啥是蓝色的捏？这个也要改成自定义的嘛？

**Comment by MokouTyan** [comment]
感谢开发，继续加油~ヽ(✿ﾟ▽ﾟ)ノ

**Comment by MokouTyan** [comment]
> @MokouTyan V3样式怎样（ https://github.com/Colter23/bilibili-dynamic-mirai-plugin/tree/v3#v3%E7%89%88%E6%9C%AC%E9%87%8D%E6%9E%84%E4%B8%AD

V2也是有一些不错的优点的，可以不用点开大图看文字
V3的话可能需要点开图才能看清文字
![image](https://user-images.githubusercontent.com/40456395/167137433-6cf311e2-0d3a-4ab1-9e24-1eab913542a5.png)
![image](https://user-images.githubusercontent.com/40456395/167137451-84abc77f-a2a1-4269-874a-14d773e53e9c.png)

**Comment by MokouTyan** [comment]
![image](https://user-images.githubusercontent.com/40456395/167137833-bf360f82-8e9a-4e30-802c-2a8b7001c729.png)
这两个感觉是有冲突的，为此我想去找这条动态，但是好像已经无了qwq

**Comment by Colter23** [comment]
关于样式以及内容我会把大多数都做成可配置的，可以自行配置
渐变色的话只要输入一个主题色就会自动生成渐变色的
这个卡片只是我用来测试的，内容都是拼凑的（你能找到就怪了

**Comment by Colter23** [comment]
一些其他组件的设计（下面这些是用设计软件画的
![画板 – 1](https://user-images.githubusercontent.com/28502163/167141199-c4afea89-00ee-4d7e-96d9-b31bc723d02a.png)

**Comment by MokouTyan** [comment]
> 一些其他组件的设计（下面这些是用设计软件画的 ![画板 – 1](https://user-images.githubusercontent.com/28502163/167141199-c4afea89-00ee-4d7e-96d9-b31bc723d02a.png)
很好看呀~卡片半透明的磨砂感，再加上渐变的背景色
我觉得如果可以的话，这两个“耳朵”可以去掉，因为有了“耳朵”卡片和背景就不是等边的了，破坏了卡片和背景的协调感觉
（单拿照片出来是挺有的设计感的，但是放在QQ里感觉还是等边比较好看一些

![image](https://user-images.githubusercontent.com/40456395/167146385-86a851d8-e43d-43d5-bddc-af69dd74d172.png)

**Comment by Colter23** [comment]
![6X5)FTJGU(8W827@HR1AW62](https://user-images.githubusercontent.com/28502163/167151486-b8603b25-a96c-468f-b438-6cb6b65f3b11.jpg)
好了，饼画好了，是时候摸鱼了
![KZ9 @T {)9VQ9U61O5SWPV0](https://user-images.githubusercontent.com/28502163/167151817-e5b6a79d-aeee-4f34-a828-185d98e7d249.gif)
v3一时半会估计是搞不完，慢慢等吧

**Comment by Colter23** [comment]
更新了测试版 [v3.0.0-M1](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.0.0-M1)
