### ISSUE TITLE
直播预约不会显示出来，是空白的，转发的直播预约也是空白的

### ISSUE THREAD

**Issue by neko886** [Colter23/bilibili-dynamic-mirai-plugin#58]
作者您好~，BOT推送主播发的直播预约动态时，发现没有显示直播预约的图，而是变成空白的。转发直播预约时直接完全空白，是我的bot没设置好吗？

这个是BOT发的。
![QQ截图20220429185813](https://user-images.githubusercontent.com/103251269/165932330-5b1e02e7-4ddd-407e-9736-01a70bd14529.jpg)

这是B动态显示的。
![QQ截图20220429185739](https://user-images.githubusercontent.com/103251269/165932343-1a95ad31-c0a3-4d27-8f92-48a982951b18.jpg)

**Comment by neko886** [comment]
嗯好的，期待~

**Comment by Colter23** [comment]
更新了测试版 [v3.0.0-M1](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.0.0-M1)
