### ISSUE TITLE
视频封面下载失败时，可不可以以文字模式推送消息

### ISSUE THREAD

**Issue by okanikubay** [Colter23/bilibili-dynamic-mirai-plugin#60]
昨天晚上遇到了不推送的情况，然后上服务器看日志发现是封面图片下载超时了，请问大佬能不能在图片下载失败时以文字形式推送消息

**Comment by Colter23** [comment]
图片下载失败应该也会推送呀（只不过图片位置空了

**Comment by okanikubay** [comment]
好吧 那可能是我服务器的网络问题 感谢回复 
![_G_K6GDTKEHD0_B8AU2BE78.png](https://s2.loli.net/2022/05/09/AeEbG3FYR2dX194.png)

**Comment by Colter23** [comment]
emmm原来是触发了这个超时（
