### ISSUE TITLE
data文件内，前一个群炸了，后面发送失败

### ISSUE THREAD

**Issue by MokouTyan** [Colter23/bilibili-dynamic-mirai-plugin#61]
无意中发现的这个bug，刚好有个群炸了，然后data文件里面订阅用户的列表有个顺序，炸的群后面的那些群，接不到消息

**Comment by MokouTyan** [comment]
就是那个群号列表的顺序
我没测试过QQ个人的（比如被好友删除了的话，bot也会找不到用户发

**Comment by Colter23** [comment]
有报错的log吗

**Comment by MokouTyan** [comment]
没有捏，但是你在群号列表前面加几个不存在的群号，应该可以直接测试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年5月10日(星期二) 下午3:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Colter23/bilibili-dynamic-mirai-plugin] data文件内，前一个群炸了，后面发送失败 (Issue #61)





 
有报错的log吗
