### ISSUE TITLE
文字排版建议   建议在图片上面也可以有文字

### ISSUE THREAD

**Issue by elysiawen** [Colter23/bilibili-dynamic-mirai-plugin#62]
想在图片上面也加上文字，来实现下面图片这样的效果。
或者可以直接将生成的图片也作为文字模板的配置项。
非常感谢大佬。
![QQ截图20220526132540](https://user-images.githubusercontent.com/46924591/170422432-e1235f76-48e6-4044-b8d5-feec7e3f66ab.png)

**Comment by Colter23** [comment]
v3会有的

**Comment by Colter23** [comment]
更新了测试版 [v3.0.0-M1](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.0.0-M1)
