### ISSUE TITLE
开启直播艾特全体后有一定概率不推送

### ISSUE THREAD

**Issue by 1146592168** [Colter23/bilibili-dynamic-mirai-plugin#63]
作者好～添加直播艾特全体权限之后有一些群不推送直播通知，本来以为所有群都开启之后都不推送，想测试一遍在控制台找记录的才发觉有一些群推送得出来orz

**Comment by Colter23** [comment]
@全体 bot需要管理员身份的（不是管理员推送不出来可能是bug

**Comment by 1146592168** [comment]
> @全体 bot需要管理员身份的（不是管理员推送不出来可能是bug

好的 感谢
