### ISSUE TITLE
仅Bot管理员可进行登录-版本2.2.2

### ISSUE THREAD

**Issue by Mr-wr** [Colter23/bilibili-dynamic-mirai-plugin#64]
想问一下
文件中
# 管理员
admin: （这个是设置什么的？）
---------------------------------
使用bili login指令后
提示：仅Bot管理员可进行登录
我该进行怎么操作呢？？

**Comment by Colter23** [comment]
在[配置文件](https://github.com/Colter23/bilibili-dynamic-mirai-plugin#%E9%85%8D%E7%BD%AE)中的第一项 `admin` 后填上你的qq号。然后在qq中 `私聊` bot进行登录

**Comment by Mr-wr** [comment]
非常感谢你能再空闲之余回复并替我解答，我按照你说的操作后，有一点不是很明白，私聊bot是指用admin的qq给bot的qq发信息吗？发什么呢？第一次弄这个不是很太明白，

**Comment by Mr-wr** [comment]
我尝试发送/bili login，bot可以收到消息，但是没有反应

**Comment by Mr-wr** [comment]
现在有了，我先在群里发/bili login然后再私聊，他回复我要管理员，（但我本来就是呀）然后我私聊，他就给我发二维码了

**Comment by Colter23** [comment]
为什么要在群里login（只有 `管理员` (这个管理员不是群里的那个管理员，而是bot的管理员，就是在配置文件中填的那个人)`私聊`发送 `/bili login` 才会给你二维码进行登录

**Comment by Mr-wr** [comment]
我也很奇怪，之前我试过了，私发没反应
然后我又去群里发了一次

然后再私发

他才出来的二维码




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年6月5日(星期天) 晚上10:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Colter23/bilibili-dynamic-mirai-plugin] 仅Bot管理员可进行登录-版本2.2.2 (Issue #64)





 
为什么要在群里login（只有 管理员 (这个管理员不是群里的那个管理员，而是bot的管理员，就是在配置文件中填的那个人)私聊发送 /bili login 才会给你二维码进行登录

**Comment by Colter23** [comment]
登录一次可以用很久，不要再纠结登录功能了（下个版本登录功能可能会有点变化
