### ISSUE TITLE
V3问题/建议反馈

### ISSUE THREAD

**Issue by Colter23** [Colter23/bilibili-dynamic-mirai-plugin#66]
QQ群（734922374

**Comment by MokouTyan** [comment]
可以喔（

**Comment by biu788** [comment]
我要手动在data里面新建font文件夹然后把字体文件放进去

**Comment by biu788** [comment]
![image](https://user-images.githubusercontent.com/105760345/174702390-7f700d86-df2b-4aa2-b3f3-b380e3634358.png)

**Comment by biu788** [comment]
哦，配置文件里面还要手动填一下字体

**Comment by biu788** [comment]
然后发动态测试没有反应

**Comment by biu788** [comment]
![image](https://user-images.githubusercontent.com/105760345/174712501-df600433-2cfd-48fd-90f1-4fb52b1cf28a.png)

**Comment by MokouTyan** [comment]
![image](https://user-images.githubusercontent.com/40456395/174715187-ee7e1cc2-820f-44d2-9b89-53b34cb1ef97.png)
我的是这样子，监测到发布动态会报错

初次运行是这样报错
![image](https://user-images.githubusercontent.com/40456395/174715244-63680517-fd54-4e9c-8652-e69ad8f63e7c.png)

**Comment by biu788** [comment]
目前纯动态好像能检测到但是发不出来

**Comment by Colter23** [comment]
> 哦，配置文件里面还要手动填一下字体

使用自定义字体是这个流程（默认字体字体好像也加载失败了

**Comment by Colter23** [comment]
@MokouTyan @biu788 [v3.0.0-M2](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.0.0-M2)

**Comment by biu788** [comment]
非常感谢！目前纯文字动态还不能转发！

**Comment by Colter23** [comment]
> 非常感谢！目前纯文字动态还不能转发！

我这可以呀，你是不是加了什么过滤器（可以去插件数据路径下看看 `BiliData.yml` 数据文件中的 `filter`

**Comment by biu788** [comment]
![image](https://user-images.githubusercontent.com/105760345/174823994-849175e5-a10c-4299-a04b-efae8dc4a2bc.png)
![image](https://user-images.githubusercontent.com/105760345/174824098-03731d98-2b8b-4c88-9888-1293b476d59f.png)

**Comment by Colter23** [comment]
这个错是怎么报的。哪个动态不能转发，能发个动态ID吗

**Comment by biu788** [comment]
> 这个错是怎么报的。哪个动态不能转发，能发个动态ID吗

刚刚的删了，现在又发了一个，也是同样的报错
https://t.bilibili.com/674239642977959952

**Comment by Colter23** [comment]
哦对，[v3.0.0-M2](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.0.0-M2) 我后面又更新了下，你用的是最新的吗

**Comment by biu788** [comment]
> 哦对，[v3.0.0-M2](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.0.0-M2) 我后面又更新了下，你用的是最新的吗

是的

**Comment by biu788** [comment]
> 哦对，[v3.0.0-M2](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.0.0-M2) 我后面又更新了下，你用的是最新的吗

嗷，没

**Comment by biu788** [comment]
好了！可以了！非常感谢！现在就等交互式配置做完了！

**Comment by Colter23** [comment]
其实那个交互式配置我还不知道怎么做比较好（挺难搞的

**Comment by biu788** [comment]
> 其实那个交互式配置我还不知道怎么做比较好（挺难搞的

别急，慢慢来

**Comment by Colter23** [comment]
建了个群 734922374

**Comment by elysiawen** [comment]
想问一下这是什么问题
![QQ截图20220623150113](https://user-images.githubusercontent.com/46924591/175236051-7fd138da-b44a-4b31-8787-9385880c9460.png)

**Comment by Colter23** [comment]
下个版本修，或者加群，群里有修复的

**Comment by zxmacc** [comment]
QwQ打扰了，大佬，那个skiko怎么安装，我是linux-x64，装的centos  8，去运行的这个 ，用的mirai-console v2.11.0，没有图形界面

**Comment by Colter23** [comment]
不用手动装呀，会自动下载的

**Comment by zxmacc** [comment]
啊这，但是我测试下来，V3全是绘制渲染失败，V2没什么影响
![O 8}XNMBN~YOBM$_TG5M0W5](https://user-images.githubusercontent.com/71143103/175797151-682e39a0-3ce6-4a25-9816-14c70688170c.png)

**Comment by zxmacc** [comment]
![)R8E}MIH0RH{1DTS74_@2BW](https://user-images.githubusercontent.com/71143103/175797345-2b5a80c9-25be-4031-9928-6b99bf22f691.png)
也没有报错信息，很迷

**Comment by zxmacc** [comment]
也没有报错信息，很迷
![C5XC_DCEZ{TYQ$VB}KNN}XP](https://user-images.githubusercontent.com/71143103/175797379-e77f93c8-9645-4d01-8f31-a6f3f7f3c27c.png)

**Comment by zxmacc** [comment]
也有可能是我缺了什么东西，突然想起来之前装[DrawMeme - 基于Skiko的奇怪的图片生成器](https://mirai.mamoe.net/topic/963/drawmeme-%E5%9F%BA%E4%BA%8Eskiko%E7%9A%84%E5%A5%87%E6%80%AA%E7%9A%84%E5%9B%BE%E7%89%87%E7%94%9F%E6%88%90%E5%99%A8?page=1)的时候，前置插件就是这个[Skiko](https://github.com/LaoLittle/SkikoMirai),然后安装完后发现报错，之后排查是发现自己少了OpenGL，然后装上就好了，附issues[linux-x64 没有那个文件或目录](https://github.com/LaoLittle/SkikoMirai/issues/5)

**Comment by zxmacc** [comment]
不行，我还是先用V2吧，QwQ，大佬加油

**Comment by Colter23** [comment]
额，那个模板就那样，会显示绘制失败，因为我还没做完（目前还是测试版（可以用 `/bili s 672758742491594756` 指令查询绘制指定动态    
另有兴趣的话可以加群，群里响应会即时一点

**Comment by zxmacc** [comment]
哦抱歉，我以为不行的，确实可以正常绘制

**Comment by YehowahLiu** [comment]
#68
