### ISSUE TITLE
我明明有权限却提示权限不足

### ISSUE THREAD

**Issue by aipiao-gh** [Colter23/bilibili-dynamic-mirai-plugin#69]
我已经把所有权限给我但是我用/bili ul他告诉我权限不足[https://img.wang.232232.xyz/img/2022/07/02/JQQ1AOQJKT4OZH17S.png](url)

**Comment by aipiao-gh** [comment]
https://img.wang/image/YsuxV

**Comment by aipiao-gh** [comment]
在后台使用bili la也说权限不足https://img.wang/image/Ysx3M

**Comment by Colter23** [comment]
你应该是用的v2版本，v2版 `lu` 跟 `la` 需要在配置文件中配置管理员，`login` 需要配置管理员后管理员 `私聊` bot。

**Comment by aipiao-gh** [comment]
我在配置文件配置了管理员可还是这样https://img.wang/image/YssS1

**Comment by Colter23** [comment]
要不你试试v3（

**Comment by aipiao-gh** [comment]
v3正常了)

**Comment by Colter23** [comment]
嗯，有兴趣可以加群，有问题可以得到及时响应。734922374

**Comment by Colter23** [comment]
嗯，有兴趣可以加群，有问题可以得到及时响应。734922374
