### ISSUE TITLE
关于订阅失败和图片发送失败的问题

### ISSUE THREAD

**Issue by WillowKoishi** [Colter23/bilibili-dynamic-mirai-plugin#7]
环境：mcl1.0.5 java11.0.10
1,订阅需订阅2次才能订阅上，第一次必失败
2，图片发送失败，已经检查mirai目录下已生成待发送图片，所以不是cookie设置问题
截图：
https://z3.ax1x.com/2021/04/15/cgtRTs.jpg
https://z3.ax1x.com/2021/04/15/cgtfkn.jpg
https://z3.ax1x.com/2021/04/15/cgthYq.jpg
另外还有mcl正常stop关闭后管理账号会变成0
https://z3.ax1x.com/2021/04/15/cgBncq.jpg

**Comment by Colter23** [comment]
不要在开启bot的情况下修改配置文件，修改的内容会在stop后还原。     
图片发送失败是因为第一次获取配置文件时没有管理账号，无法上传。      
订阅2次是因为第一次其实已经订阅上了，只是图片发送失败，所以报错了。     

请在开启bot**之前**设置好所有的配置(尤其是**管理员账号**)，**保存并关闭**   再启动bot。
如果还不好的话，可以试试新版的文字推送模式，少了生成图片，会少很多问题。    
感谢使用( •̀ ω •́ )✧
