### ISSUE TITLE
Error: libskiko-linux-x64.so: libGL.so.1:  No such file or directory 无法打开共享对象文件: 没有那个文件或目

### ISSUE THREAD

**Issue by skyfsj** [Colter23/bilibili-dynamic-mirai-plugin#71]
#### 开启时报错
![1](https://user-images.githubusercontent.com/47785500/177909401-1adeb2a0-7d34-4a34-8497-c8e80f0a10e9.png)
#### 尝试渲染时报错
![2](https://user-images.githubusercontent.com/47785500/177909512-085dbafc-61b7-4e39-b319-b530eee1cb99.png)

### 解决方法
安装：OpenGL Library
`sudo apt-get install libgl1-mesa-dev`
参考资料：https://blog.csdn.net/csp123258/article/details/82626042

**Comment by YuanNing-96** [comment]
使用系统：ubuntu server 20.04
补充一下，对于这条命令
sudo apt-get install libgl1-mesa-dev
如果执行失败，（我忘记当时出现的错误是什么了
可以考虑更新ubuntu到最新版，我更新到22.04就好使了
