### ISSUE TITLE
登录命令发出后还没扫码就提示登录失败

### ISSUE THREAD

**Issue by xianyu1124** [Colter23/bilibili-dynamic-mirai-plugin#74]
登录失败 No transformation found: class io.ktor.utils.io.ByteBufferChannel -> class top.colter.mirai.plugin.bilibili.data.LoginResult
with response from http://passport.bilibili.com/qrcode/getLoginInfo:
status: 200 OK
response headers: 
access-control-allow-credentials: true
, access-control-allow-headers: Origin,No-Cache,X-Requested-With,If-Modified-Since,Pragma,Last-Modified,Cache-Control,Expires,Content-Type,Access-Control-Allow-Credentials,DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Cache-Webcdn,x-bilibili-key-real-ip,x-backend-bili-real-ip,x-risk-header
, access-control-allow-origin: https://t.bilibili.com
, bili-status-code: 0
, cache-control: no-cache
, connection: keep-alive
, content-length: 50
, content-type: application/json;charset=UTF-8
, cross-origin-resource-policy: cross-origin
, date: Sun, 24 Jul 2022 05:40:40 GMT
, expires: Sun, 24 Jul 2022 05:40:39 GMT
, server: Apache-Coyote/1.1
, set-cookie: sid=n5c2he6q; Domain=.bilibili.com; Expires=Mon, 24-Jul-2023 05:40:40 GMT; Path=/
, x-cache-webcdn: BYPASS from blzone05

**Comment by Colter23** [comment]
暂时手动填写cookie吧

**Comment by Colter23** [comment]
[v3.0.0-BETA4](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.0.0-BETA4) 修了
