### ISSUE TITLE
文字版发送的附件图是否能支持gif

### ISSUE THREAD

**Issue by SekiBetu** [Colter23/bilibili-dynamic-mirai-plugin#8]
![IMG_20210419_160942](https://user-images.githubusercontent.com/38283893/115203135-b6f25d00-a129-11eb-8153-2b83c753bed5.jpg)
如图，发送的图片都是静态图片，而不是gif

**Comment by Colter23** [comment]
嗯，之后会支持的( •̀ ω •́ )✧

**Comment by SekiBetu** [comment]
> 嗯，之后会支持的( •̀ ω •́ )✧

大佬辛苦了，很喜欢这种小而简单的插件

**Comment by Colter23** [comment]
好了，修好了. [releases]( https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/1.0.3) 里已更新
