### ISSUE TITLE
为已经退出的群取消订阅

### ISSUE THREAD

**Issue by AustinGYF** [Colter23/bilibili-dynamic-mirai-plugin#80]
请问一下可以为已经退出的群取消订阅吗。
如果可以的话具体怎么操作？

**Comment by KaRuichin** [comment]
`\data\top.colter.bilibili-dynamic-mirai-plugin\BiliData.yml`

**Comment by Colter23** [comment]
https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.2.1
