### ISSUE TITLE
安卓端文字推送模式GIF图片空白

### ISSUE THREAD

**Issue by SekiBetu** [Colter23/bilibili-dynamic-mirai-plugin#9]
如图，gif图点开后空白，是否是因为gif文件体积太大了用mirai无法发送？
![Screenshot_2021-04-20-16-09-46-407_com tencent mobileqq](https://user-images.githubusercontent.com/38283893/115361383-1c5e5080-a1f3-11eb-822e-821ebe1c725c.jpg)
![Screenshot_2021-04-20-16-09-52-893_com tencent mobileqq](https://user-images.githubusercontent.com/38283893/115361394-1ff1d780-a1f3-11eb-8fcb-90b0c7310e6b.jpg)

**Comment by SekiBetu** [comment]
看了下，接受到的文件名字是gif，仍为静态图，只有137k，而原本的gif有8m大小

**Comment by SekiBetu** [comment]
应该是只改了推送功能，而接收功能仍然是接收jpg图片？

**Comment by Colter23** [comment]
我之前自测是好用的呀。。。我再试试

**Comment by SekiBetu** [comment]
好像电脑上能看到gif图，安卓上是静态的

**Comment by Colter23** [comment]
嗯，确实，我电脑上是好的，但手机上也看不了

**Comment by SekiBetu** [comment]
mirai框架拉胯了？

**Comment by Colter23** [comment]
不是到是mirai的锅还是qq的锅，或者是我上传的方式不对。。

**Comment by Colter23** [comment]
经过多次测试，感觉是QQ的问题，用一台手机给另一台发送gif，另一台也是无法显示的，你也可以再试试。

**Comment by SekiBetu** [comment]
先放着吧，有可能腾讯的问题，不管了

**Comment by Colter23** [comment]
应该是mirai的问题，已经在mirai提issues了，看能不能解决吧

**Comment by SekiBetu** [comment]
https://github.com/mamoe/mirai/issues/1204
fixed
