### ISSUE TITLE
经常下载图片失败

### ISSUE THREAD

**Issue by kokorousaki** [Colter23/bilibili-dynamic-mirai-plugin#92]

**Comment by kokorousaki** [comment]
图片我试过了，可以下载

**Comment by kokorousaki** [comment]
![@Y5(ZDJ$K(9%PMYG_LZN(`D](https://user-images.githubusercontent.com/87707351/219987789-78cbfdbc-18bd-45c8-9fb4-aef6a7de72b8.png)
效果图

**Comment by kokorousaki** [comment]
版本号3.2.4，之前3.2好像都有这个问题，就是程序运行久了就有好像

**Comment by Colter23** [comment]
可能你动态太多，图片下载太频繁？被b站限制了（我目前还没遇到过

**Comment by jexjws** [comment]
我也遇到了一样的问题，我看报错显示的是time out，

所以我猜应该是图片还没来得及下完，这边就超时错误地判定为失败了

如果bot下载图片下的是原图的话

**Comment by jexjws** [comment]
可不可以给一个修改超时时间的手段，方便排错？

**Comment by Colter23** [comment]
超时时间很长的。而且现在bot会下两版图片，第一版原图，如果下载失败就下载压缩图。应该是网络问题，目前我也么什么好的解决办法，你可以试试代理（

**Comment by Colter23** [comment]
@kokorousaki  [v3.2.6](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.2.6) 尝试修复，可以试试，自行修改配置，有问题可继续反馈

**Comment by kokorousaki** [comment]
> @kokorousaki [v3.2.6](https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.2.6) 尝试修复，可以试试，自行修改配置，有问题可继续反馈

今天才看到，在测了ing，感谢

**Comment by kokorousaki** [comment]
![QQ截图20230419092523](https://user-images.githubusercontent.com/87707351/232942868-9a2a0c7a-c84a-47f5-8475-be937e705b08.jpg)
最近经常看到这种断开的日志，是网络问题或是B站的问题吗？

**Comment by Colter23** [comment]
这跟插件/B站没关系吧，是mirai/qq的问题，这种重连很正常
