### ISSUE TITLE
/bili s生成动态，如果动态已经删除，没有回复

### ISSUE THREAD

**Issue by SVIPNB** [Colter23/bilibili-dynamic-mirai-plugin#97]
/bili s 770557832244232209想要生成一个动态，但是没有任何回复，后来发现是因为动态已删除。
https://api.bilibili.com/x/polymer/web-dynamic/v1/detail?timezone_offset=-480&id=770557832244232209
动态链接https://www.bilibili.com/770557832244232209

**Comment by Colter23** [comment]
https://github.com/Colter23/bilibili-dynamic-mirai-plugin/releases/tag/v3.2.5
